name: check
on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check
        run: |
          git pull
          rm -rf *.txt
          git clone https://github.com/dnscrypt/dnscrypt-resolvers.git
          cp .github/workflows/relaycheck.sh dnscrypt-resolvers/.github/workflows/relaycheck.sh
          cd dnscrypt-resolvers
          curl https://download.dnscrypt.info/dnscrypt-resolvers/json/public-resolvers.json | grep -B 12  -A 1 '"proto": "DNSCrypt",' | grep  -A 14 '"dnssec": true,' | grep  -A 13 '"ipv6": false,' | grep  -A 6 -B 1 '"nofilter": false,' | grep  -A 5 -B 3 '"nolog": true,'| sed -e '/nofilter/d' -e '/nolog/d' -e '/ports/{N;d;}' -e '/proto/d' -e '/]/d' -e '/family/,+2d' -e '/sfw/,+2d' -e '/nogoogle/,+2d'  -e '/adguard/,+2d' -e '/cleanbrowsing/,+2d' -e '/quad9/,+2d' -e 's/"name":/##/g' -e 's/"//g' -e 's/stamp: sdns:/sdns:/g' -e 's/,//g' -e 's/^[ \t]*//' > v3/public-resolvers.md
          .github/workflows/resolverscheck.sh | tee resolverscheck
          sort -u resolverscheck | tee ../resolverscheck
          chmod +x .github/workflows/relaycheck.sh
          .github/workflows/relaycheck.sh | tee relaycheck
          sort -u relaycheck | tee ../relaycheck
          rm -rf ../dnscrypt-resolvers
      - name: commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit --allow-empty -m "$(git log -1 --pretty=%s)"
          git push
          
